site_name: Citrix Hypervisor Changed Block Tracking Guide
site_description: Citrix Hypervisor Changed Block Tracking Guide
site_title: Developer Documentation

copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

theme:
  name: null
  custom_dir: material
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png
  
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta

nav:
- Introduction: index.md
- Getting Started: getting-started.md
- Enabling NBD connection: enabling-nbd.md
- Using CBT with a VDI: using-with-vdi.md
- Deleting VDI snapshots: deleting-snapshot.md
- Getting the list of changes blocks in a VDI: list-changed-blocks.md
- Exporting changed blocks over NBD: exporting-changed-blocks.md
- Coalescing changed blocks onto a base VDI: coalescing-blocks.md
- Appendices: appendices.md
